services:
  django:
    image: realestateapp
    volumes:
      - C:/apps/Realestate/realestateapp/static:/app/realestateapp/static/
      - C:/apps/Realestate/realestateapp/media:/app/media/
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - C:/apps/Realestate/certificates:/etc/letsencrypt/  # Mount the certificates directory
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - C:/apps/Realestate/realestateapp/static:/var/www/static/
      - C:/apps/Realestate/realestateapp/media:/var/www/media/
    ports:
      - "443:443"  # Ensure HTTPS port is exposed
      - "80:80"    # Optional: for HTTP to HTTPS redirection
    networks:
      - webnet

volumes:
  static_volume:
  media_volume:

networks:
  
  webnet: