services:
  django:
    image: realestate
    volumes:
      - C:/apps/Realestate/realestateapp/static:/app/realestateapp/static/
      - C:/apps/Realestate/realestateapp/media:/app/media/
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - C:/apps/Realestate/realestateapp/static:/var/www/static/
      - C:/apps/Realestate/realestateapp/media:/var/www/media/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:8081"
    networks:
      - webnet

volumes:
  static_volume:
  media_volume:

networks:
  webnet: