# Generated by Django 3.1.1 on 2024-04-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(default='Shtepi', max_length=100),
        ),
    ]
