# Generated by Django 3.1.1 on 2024-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='virtual_tour',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
