# Generated by Django 3.1.1 on 2024-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_virtual_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cadastral_record',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='google_location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
