# Generated by Django 3.1.1 on 2024-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20240514_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='google_location',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
