# Generated by Django 3.1.1 on 2024-05-21 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20240514_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/<django.db.models.fields.CharField>'),
        ),
    ]
