# Generated by Django 3.1.1 on 2024-05-07 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtors', '0002_auto_20240507_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
